### ISSUE TITLE
Yaml roadmap

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#197]
Pour essayer de clarifier un peu ce qui a été fait et ce qui reste à faire:

- [x] Utilisation complète de yaml pour gérer les contenu des fichiers .sb #190 
- [x] Passer tous les tests et les exemples au format yaml #198
- [x] Renommer `.sb` en `.yaml` (avec complétion automatique lors du `build` ?) #198
- [x] Gérer les traductions des options par défaut et des descriptions de ces options
- [ ] Mettre la doc à jour (notamment pour le format du fichier `.yaml` (branche [patacrep-doc/yaml](https://github.com/patacrep/patacrep-doc/tree/yaml) et issue https://github.com/patacrep/patacrep-doc/issues/15)

@paternal : n'hésite pas à éditer directement ce message

**Comment by oliverpool** [comment]
La branche `yaml_content` est prête à être mergé dans `yaml` : tous les types de contenus sont supportés et testés.

Il faudrait ensuite vérifier que les tests et les exemples sont au format yaml (et non json) par soucis de cohérence (et de lisibilité).

Le renommage en `.yaml` ne devrait pas demander longtemps (mais je pense qu'il est sage d'attendre la résolution des points précédents)

Pour les traductions, je ne sais pas encore trop comment faire (utiliser `gettext` me parait pas très évident). Peut-être qu'il faudrait une issue dédiée pour faire des propositions.

**Comment by paternal** [comment]
> Pour les traductions, je ne sais pas encore trop comment faire (utiliser gettext me parait pas très évident). Peut-être qu'il faudrait une issue dédiée pour faire des propositions.

Vu qu'on est parti sur Rx, je pense qu'on peut abandonner et repartir sur quelque chose du même genre de ce qu'on avait avant : [ton brouillon](https://github.com/patacrep/patacrep/blob/957cb756c8dcaf700154542f09870b0991918c78/patacrep/data/templates/default.tex#L36-L39) me parait bien. Sauf peut-être, pour faciliter la lecture : 
~~~yaml
description:
    en:
        title: "The title of the songbook"
default:
    en:
        title: "A wonderful title"
~~~

**Comment by paternal** [comment]
> Vu qu'on est parti sur Rx, je pense qu'on peut abandonner et repartir sur quelque chose du même genre de ce qu'on avait avant

J'ai oublié un mot : « on peut abandonner *gettext* ».

**Comment by oliverpool** [comment]
Ca marche, je m'y attaquerai après le merge de #198

**Comment by paternal** [comment]
On peut merger, non ? Pour la doc, c'est dans `patacrep-doc`, donc on n'oubliera pas.

**Comment by oliverpool** [comment]
J'ai fait un merge back pour une dernière revue (le merge a été assez douloureux...)
